version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/postgres
    depends_on:
      - db
    stdin_open: true
    volumes:
      - ./backend/:/app/backend/
    command: >
      sh -c "
        cd /app/backend/apps/api/src;
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  db:
    image: postgres:14.10-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_14_10:/var/lib/postgresql/data

volumes:
  postgres_14_10:
