name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths:
      - "pnpm-lock.yaml"
      - ".github/workflows/frontend.yml"

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Run linter
        run: pnpm run lint:full
